### ISSUE TITLE
Clicking the book on the desk doesn't do anything

### ISSUE THREAD

**Issue by corysimmons** [superguigui/guillaumegouessan.com#1]
I know this isn't the repo for your current site but figured I'd reach out to let you know clicking the book might be bugged. I'm not getting errors in the console, but hovering the book looks like it should be clickable, then clicking it doesn't seem to do anything.

Cool site!

**Comment by jovylle** [comment]
this is interesting.

**Comment by superguigui** [comment]
Wow sorry guys I completely missed those comments... So more than one year later an answer (😅) the book does something, it triggers a small animation on the UI that itself is an hint of what should be done to get the last easter egg (let's be real it's not super great though haha).
Thanks for your interest for my little website :)
By the way this repo is actually for an older version of my website which is completely different, I will archive it to reduce confusion :)
